### PR TITLE
Comment based help

### PR DESCRIPTION
**Pull request by ghost**
In reference to issue #12

### CODE REVIEW

**Comment by vexx32** [comment]
This looks great! I have one or two comments though. One is that from the commit comparison it looks like it added an extra couple spaces to all the function lines when you put the help in. Not sure if that was intentional, but I've never seen it laid out like that.

Second thing is a parameter description or two needs tweaking:
```PowerShell
<# ...
.Parameter Clear
        Clear the screen before giving feedback. Defaults to True.
    .Parameter Meditate
        Opens your local koan folder.
    .Parameter Reset
        Resets everything in your local koan folder to a blank slate. Use with caution.
... #>
```
Also, the one in `Initialize-KoanDirectory` with the switch, that basically skips the prompt to confirm deletion / overwrite. (Reminds me, I should probably set it to prompt for confirmation by default, gotta raise that ConfirmImpact to High, or else just set `-Confim:$true` in the Get-Enlightenment call for it.)

Finally, looks like you use 2 space indents, and I'd prefer it we kept it consistent (everything else is at 4 spaces atm) 😄

**Comment by BrandonLundt** [comment]
I believe I have the formatting resolved. And the parameter sections are updated.

One question on the Initialize-KoanDirectory. I'm really not clear on the purpose of FirstImport. If I call
`Initialize-KoanDirectory -FirstImport -Whatif`
I get the whatIf message AND copy-item still executes. Seems unusual/unexpected, as such not sure how to write the purpose of that parameter.

**Review by vexx32 — CHANGES_REQUESTED** [review]
Lines 210 and 214 here remove the $script: prefix on $script:KoanFolder.

I actually don't know if that _breaks_ it, but I'd prefer it were explicit either way that the variable doesn't originate in the function itself. Especially with the if test keeping the prefix, it's unclear whether the two are different or not.

**Review by vexx32 — APPROVED** [review]

**Comment by vexx32** [comment]
Looks good, I'll merge it in. 😄

**Pull request merged**
